name: deploy gh-pages
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET: ${{secrets.ACTION_SECRET}}
      PUBLISH_DIR: ./
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v1
      - name: install_sass_compiler
        run: |
          npm i -g sass
      - name: compile_scss_file
        run: |
          sass scss:css
      - name: Commit files
        run: |
          git config --local user.name githubaction
          git config --local user.email githubaction@fake.com
          git status
          git checkout -b gh-pages
          git push origin gh-pages
          echo 🤘 deploy gh-pages complete.
